import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/ui/globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import { inter } from "@/app/ui/fonts";
import Head from "next/head";
import "@/app/lib/fontawesome";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Pietro Costanzi Fantini</title>
      </Head>
      <body className={`${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
